### ISSUE TITLE
What app do i need to download on my ipad?

### ISSUE THREAD

**Issue by kemal023** [cgarwood/homeassistant-fullykiosk#106]
I'm trying to add my ipad to home assistant - minimalist. but it tells me that I need to install the Kiosk app. but wich one is that ? there are a lot of kiosk apps

**Comment by cgarwood** [comment]
This integration only works with Fully Kiosk Browser, which is Android-only. Unfortunately, I'm not familiar with the kiosk offerings in the Apple ecosystem. The regular Home Assistant app might be the best way to go.
