### ISSUE TITLE
Add services

### ISSUE THREAD

**Issue by cgarwood** [cgarwood/homeassistant-fullykiosk#13]
Add services for the following API commands. Will require some updates to the python-fullykiosk library as well.
- [ ] /?cmd=loadStartUrl&password=[pass]
- [ ] /?cmd=loadUrl&url=[url]&password=[pass]
- [ ] /?cmd=restartApp&password=[pass] 
- [ ] /?cmd=startApplication&package=[pkg]&password=[pass]
- [ ] /?cmd=toForeground&password=[pass]

- [ ] Generic set configuration service
/?cmd=setBooleanSetting&key=[key]&value=[true|false]&password=[pass] 
/?cmd=setStringSetting&key=[key]&value=[value]&password=[pass]

**Comment by cgarwood** [comment]
I think entity services will be the easiest, I haven't been able to come up with a good way to use general services and specifying which config entry to target. I'm leaning towards the media_player entity being the best target for most of the services... unless there's a way we can use entity services  that target any entity of a config entry?

**Comment by bjw-s** [comment]
I just looked at how the Hue component does this for example, and the idea seems to be that any general service runs on all config entries. There also doesn't seem to be a way to determine the config entry, so I guess that means the services have to be defined on a single entity :/ I was favoring the media_player entity for this as well, so I'll add them there 👍

**Comment by bjw-s** [comment]
I've added almost all services that are in this list. I've created a PR for the `python-fullykiosk` project to support `setBooleanSetting` and `setAudioVolume`. Once that is approved I can finish the last bits.

**Comment by cgarwood** [comment]
PR #22 merged and services added 😃  Thanks again @bjw-s !
