### ISSUE TITLE
Add volume control to media_player platform

### ISSUE THREAD

**Issue by cgarwood** [cgarwood/homeassistant-fullykiosk#2]
`/?cmd=setAudioVolume&level=[0-100]&stream=[1-10]&password=[pass]`

**Comment by bjw-s** [comment]
I tried taking a crack at implementing this, but I had to resort to using `self.controller.sendCommand`. That seems like a bit of a smell, I guess it would be cleaner to add a function to the `python-fullykiosk` module first and calling that from this component?

**Comment by bjw-s** [comment]
This one seems ✅ too 😀
