### ISSUE TITLE
cant install integration

### ISSUE THREAD

**Issue by kloodhu** [cgarwood/homeassistant-fullykiosk#24]
Installed via hass.
Try to add as Integration, but raise this error:

Logger: custom_components.fullykiosk.config_flow
Source: custom_components/fullykiosk/config_flow.py:54
Integration: Fully Kiosk Browser (documentation)
First occurred: 4:37:37 PM (1 occurrences)
Last logged: 4:37:37 PM
Unexpected exception

Traceback (most recent call last):
  File "/config/custom_components/fullykiosk/config_flow.py", line 88, in async_step_user
    info = await validate_input(self.hass, user_input)
  File "/config/custom_components/fullykiosk/config_flow.py", line 54, in validate_input
    fully = FullyKiosk(data["host"], data["port"], data["password"])
TypeError: __init__() missing 1 required positional argument: 'password'

Home Assistant 0.117.3

Ofcourse i type the password.

What can i do?

Thank you!

**Comment by cgarwood** [comment]
Just released a patch, please update through HACS and let me know if it still doesn't work.

**Comment by kloodhu** [comment]
thank you for the fast response!
Unfortunately another error gas raised:



Logger: custom_components.fullykiosk.config_flow
Source: custom_components/fullykiosk/config_flow.py:49
Integration: Fully Kiosk Browser (documentation)
First occurred: 8:48:48 AM (1 occurrences)
Last logged: 8:48:48 AM
Unexpected exception

Traceback (most recent call last):
  File "/config/custom_components/fullykiosk/config_flow.py", line 84, in async_step_user
    info = await validate_input(self.hass, user_input)
  File "/config/custom_components/fullykiosk/config_flow.py", line 49, in validate_input
    session = async_get_clientsession()
TypeError: async_get_clientsession() missing 1 required positional argument: 'hass'

**Comment by cgarwood** [comment]
doh, that's what I get for not testing it on my system 😅
Will get another patch out today

**Comment by cgarwood** [comment]
Should be fixed now & tested on my system. Give it another shot :)

**Comment by kloodhu** [comment]
thank you buddy! its working.
