### ISSUE TITLE
How does it work?

### ISSUE THREAD

**Issue by comedido** [cgarwood/homeassistant-fullykiosk#32]
I installed it via HACS (custom integration using github url). Now I wonder how to configure it and add cards to my lovelace panels.
Any pointer will be appreciated please

**Comment by cgarwood** [comment]
After installing with HACS you'll need to restart Home Assistant. Then you can add a tablet by going to Configuration -> Integrations -> Add Integration -> and find Fully Kiosk Browser in the integration list.

Remote Administration and a remote administration password will need to be enabled on the tablet.

**Comment by comedido** [comment]
That's the thing, when I try to add the "Fully Kiosk Browser" integration in the configuration it does not show up. I Installed the latest version in HACS, also tried reinstalling and selecting the master version instead.

**Comment by cgarwood** [comment]
Try forcing a refresh on the page (Ctrl-F5), I've seen the list get cached and not show new integrations a few times

**Comment by comedido** [comment]
Solved thanks, it was a matter of waiting :)
