### ISSUE TITLE
Add switch for motion detection. 

### ISSUE THREAD

**Issue by SamMousa** [cgarwood/homeassistant-fullykiosk#46]
This is not the same as #3.

It'd be great if there was a switch to disable fkb motion detection, for example when watching a movie in a dark room the detection will keep turning on the display.

An easy switch to disable that would be great!

**Comment by SamMousa** [comment]
Implemented in #47

**Comment by PhilippeRaven** [comment]
Hi there,
I'm using version 0.1.5 and can't find the entity to turn on/off the motion sensor. Using a Fire HD 10 last generation. Do you have any idea why ? Thanks for this feature anyway !
