### ISSUE TITLE
Pluggin In Device Class

### ISSUE THREAD

**Issue by joshtbernstein** [cgarwood/homeassistant-fullykiosk#5]
Would it be possible to set the device class for the pluggin in binary sensor to "plug"?

Also shouldn't it be called "plugged in" vs "pluggin in"?

**Comment by cgarwood** [comment]
Yeah, "pluggin in" is a typo, good catch.

Should be pretty simple to set the device class for that as well. Will try to take care of that today or tomorrow.

**Comment by cgarwood** [comment]
Fixed in c7342c754cd8761d2e63e03ae18491d5058a886b & new release published
