### ISSUE TITLE
Configuration Method Missing

### ISSUE THREAD

**Issue by greg520820** [cgarwood/homeassistant-fullykiosk#55]
Not getting any prompt/method to enter configuration for fully kiosk tablet.   Installed the fullykiosk integration using HACS. It shows up on the  HACS integration page, but there isn't any way to configure. Have uninstalled and installed several times.  I'm able manually install the tablet using rest and retrieve and control the fully kiosk api. Tablet is running fully kiosk version 1.44 fireOS.

Version | core-2021.9.4
Installation Type | Home Assistant OS
Development | false
Supervisor | true
Docker | true
User | root
Virtual Environment | false
Python Version | 3.9.6
Operating System Family | Linux
Operating System Version | 5.10.62
CPU Architecture | x86_64

**Comment by cgarwood** [comment]
You may need to force-refresh (Ctrl-F5) your browser on the Configuration -> Integrations page before it will show up in the Add Integration list

**Comment by greg520820** [comment]
Thanks, that resolved the issue.
