### ISSUE TITLE
Device Owner, how to?

### ISSUE THREAD

**Issue by pickonedev** [cgarwood/homeassistant-fullykiosk#65]
Hi!

Any idea how to set the tablet as device owner for Fully? (not cloud or something)

Thanks!

**Comment by pickonedev** [comment]
@cgarwood Any help, please? 🥇

**Comment by cgarwood** [comment]
Not sure on that, may be better to reach out to the developers of the Fully Kiosk Browser app. I'm guessing the steps are different depending on what kind of tablet you have and what Android version it's running.
