### ISSUE TITLE
FR : add button platform ?

### ISSUE THREAD

**Issue by chpego** [cgarwood/homeassistant-fullykiosk#73]
Instead using media_player, for example "restart fully or reboot the device"

i try to adapt the code in [WLED integration / button entity](https://github.com/home-assistant/core/blob/dev/homeassistant/components/wled/button.py) in the FKB, but it's failed

**Comment by cgarwood** [comment]
I was actually looking into this yesterday but didn't have it PR ready yet.

**Comment by chpego** [comment]
okay i will add the PR tonight ;)

**Comment by cgarwood** [comment]
PR posted: https://github.com/cgarwood/homeassistant-fullykiosk/pull/74
