### ISSUE TITLE
[Question] Possibility to add integration to HACS

### ISSUE THREAD

**Issue by somejavadev** [cgarwood/homeassistant-fullykiosk#79]
Hi,

Awesome project, Is it possible to add this to HACS for easy notifications of newer versions etc?

**Comment by cgarwood** [comment]
It should already be in HACS 🙂
https://github.com/hacs/default/blob/91e5da47ccbf55e6a07bcc5e4a26607bf9405780/integration#L99

**Comment by somejavadev** [comment]
Thanks @cgarwood, for some reason it wasn't displaying when I searched for it but after a refresh I found it.
