### ISSUE TITLE
Sensor last app start uses wrong date/time format

### ISSUE THREAD

**Issue by gerard33** [cgarwood/homeassistant-fullykiosk#84]
The sensor for last app start doesn't use the correct time format so the HA front-end will mix up the day and month order.

The first example is from a sensor with the correct date/time format and the second from this integration.
![image](https://user-images.githubusercontent.com/11230573/149396293-1a939a1f-c399-4094-892e-2829fa99c659.png)

This leads to showing 1 September instead of 9 January.
![image](https://user-images.githubusercontent.com/11230573/149396462-9cef2664-bf8f-410f-81db-1f8923e91b5a.png)

**Comment by 4g3nt0r4ng3** [comment]
This also breaks the history when paired with mysql recording.

**Comment by Puebllo** [comment]
same problem as @4g3nt0r4ng3 reports. @cgarwood any updates on this topic ?

**Comment by bcutter** [comment]
Copy that. Small issue with a bit of impact.

**Comment by chpego** [comment]
if someone has the time to adapt what is in this [PR](https://github.com/home-assistant/core/pull/52671), to fix the bug from here
