### ISSUE TITLE
Displays incorrectly on wall tablet after update then eventually crashed

### ISSUE THREAD

**Issue by ukgaz1987** [cgarwood/homeassistant-fullykiosk#98]
Since updating to HA 2022.5, when the dashboard loads on my wall tablet, it enlarges everything and then eventually crashes Fully Kiosk

Had to revert back to HA 2022.4.7 as the dashboards are not usable.

Pictures uploaded for reference

![Dashboard normal](https://user-images.githubusercontent.com/93836537/168120335-81e9f71c-e401-4452-86f4-e8a8ab6e5c03.jpg)
![Dashboard enlarged](https://user-images.githubusercontent.com/93836537/168120347-ca7ec40c-42fb-4add-a488-749ab46f7ac0.jpg)

**Comment by cgarwood** [comment]
This integration has no control over how the frontend is displayed on the tablet. This is most likely related to a HA frontend update.
